# Add line gap between prompt and output of previous command.
# add_newline = false

# Starship will display the prompt after command_timeout ms. It will ignore the modules that take a time greater than command_timeout ms to load.
command_timeout = 500

# Right format should be removed since we're using $fill
# right_format = """$cmd_duration$memory_usage"""
format = "$all$fill$cmd_duration$memory_usage$line_break$character"

[fill]
symbol = ' '

[line_break]
# Prompt is one line, not two lines
disabled = false

# Left prompts
[localip]
format = '[$localipv4]($style) '
ssh_only = true
disabled = false

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
stashed = "$${count}"

# Right prompts
# [[battery.display]]
# threshold = 100

[cmd_duration]
format = '[$duration]($style) '
style = 'dimmed white'
min_time = 0

[memory_usage]
format = '$symbol[${ram}(|${swap})]($style) '
style = 'dimmed white'
symbol = ' '
threshold = -1
disabled = false
